import React,{useRef,Suspense} from 'react';
import {Canvas,extend,useFrame} from '@react-three/fiber';
import {Environment,Lightformer,shaderMaterial,Line,Html} from '@react-three/drei';
import * as THREE from 'three';
import {content} from './content';
// Adjust uRose for the warm glow. uDark is the dark background. The fragment shader
// mixes a slowly drifting Gaussian gradient with fine screen-space film grain.
const AmbientMaterial=shaderMaterial({uTime:0,uRose:new THREE.Color('#57352f'),uDark:new THREE.Color('#0e0c0d')},
`varying vec2 vUv;void main(){vUv=uv;gl_Position=projectionMatrix*modelViewMatrix*vec4(position,1.);}`,
`uniform float uTime;uniform vec3 uRose;uniform vec3 uDark;varying vec2 vUv;float hash(vec2 p){return fract(sin(dot(p,vec2(12.9898,78.233)))*43758.5453);}void main(){vec2 p=vUv-vec2(.62+.03*sin(uTime*.15),.48);float g=exp(-dot(p*vec2(1.1,1.5),p*vec2(1.1,1.5))*9.);vec3 c=mix(uDark,uRose,g*.6);c+=(hash(gl_FragCoord.xy)-.5)*.035;gl_FragColor=vec4(c,1.);}`);
extend({AmbientMaterial});
// Edit these Bezier control points to change the heart silhouette; bevelSize and
// bevelThickness below control its soft, inflated edges.
const shape=new THREE.Shape();shape.moveTo(0,.55);shape.bezierCurveTo(.85,1.65,2,.65,1.25,-.2);shape.bezierCurveTo(.9,-.8,.35,-1.1,0,-1.5);shape.bezierCurveTo(-.35,-1.1,-.9,-.8,-1.25,-.2);shape.bezierCurveTo(-2,.65,-.85,1.65,0,.55);
function Scene({reduced,mobile}){const heart=useRef(),ambient=useRef();useFrame(({clock,pointer})=>{if(reduced)return;const t=clock.elapsedTime;if(ambient.current)ambient.current.uTime=t;if(heart.current){heart.current.rotation.y=Math.sin(t*.24)*.22+pointer.x*.13;heart.current.rotation.x=-.12+pointer.y*.08;heart.current.rotation.z=-.14+Math.sin(t*.3)*.04;heart.current.position.y=Math.sin(t*.7)*.07;}});return <><mesh position={[0,0,-4]}><planeGeometry args={[30,20]}/><ambientMaterial ref={ambient}/></mesh><ambientLight intensity={.6}/><spotLight position={[4,6,4]} intensity={85} color="#f5d5c8"/><mesh ref={heart} rotation={[-.12,.18,-.14]} scale={mobile?.83:1.1}><extrudeGeometry args={[shape,{depth:.36,bevelEnabled:true,bevelSegments:mobile?5:12,steps:1,bevelSize:.3,bevelThickness:.34,curveSegments:mobile?20:48}]}/>{/* Raise roughness for frost; lower metalness for clearer liquid glass. */}<meshPhysicalMaterial color="#eab6a0" metalness={.64} roughness={.13} transmission={mobile?0:.38} thickness={1.2} ior={1.45} clearcoat={1} envMapIntensity={2}/></mesh><Environment resolution={mobile?64:128}><Lightformer position={[-3,2,3]} scale={[2,7,1]} intensity={5} color="#fff5eb"/><Lightformer position={[4,0,1]} scale={[2,5,1]} intensity={4} color="#d79075"/><Lightformer position={[0,-4,2]} scale={[6,1,1]} intensity={3} color="#fcf7f0"/></Environment></>}
class Boundary extends React.Component{state={failed:false};static getDerivedStateFromError(){return {failed:true}}render(){return this.state.failed?<div className="webgl-fallback">love, in every dimension.</div>:this.props.children}}
export function HeartScene({reduced,mobile,visible=true}){return <Boundary><Canvas dpr={[1,mobile?1.25:1.7]} frameloop={reduced||!visible?'demand':'always'} camera={{position:[0,0,7],fov:40}} gl={{antialias:!mobile,alpha:false}}><Suspense fallback={null}><Scene reduced={reduced} mobile={mobile}/></Suspense></Canvas></Boundary>}
// Distribute nodes from the editable memory list, including added memories.
const positions=content.memories.map((_,i,all)=>[all.length===1?0:-3+6*i/(all.length-1),Math.sin(i*2.2)*.65,(i%3-1)*.3]);
function Stars({progress,reduced,mobile,active,onSelect}){const group=useRef();useFrame(({camera,clock})=>{if(reduced||mobile)return;camera.position.z=8-progress.current*1.4;if(group.current)group.current.rotation.y=Math.sin(clock.elapsedTime*.15)*.06});return <group ref={group}><Line points={positions} color="#ac7865" transparent opacity={.5} lineWidth={1}/>{positions.map((p,i)=><group key={i} position={p}><mesh><sphereGeometry args={[active===i?.09:.05,12,12]}/><meshBasicMaterial color="#f5d5c8"/></mesh><Html center distanceFactor={8}><button aria-label={`Open memory ${i+1}`} aria-pressed={active===i} className={`star-node ${active===i?'active':''}`} onClick={()=>onSelect(i)} onPointerEnter={()=>onSelect(i)}><span className="node-halo"/><span className="node-label">0{i+1}</span></button></Html></group>)}{Array.from({length:mobile?24:55},(_,i)=><mesh key={i} position={[Math.sin(i*73)*7,Math.cos(i*47)*3,-2-i%5]}><sphereGeometry args={[.008+i%3*.003,4,4]}/><meshBasicMaterial color="#ba978c"/></mesh>)}</group>}
export function Constellation(props){return <Boundary><Canvas camera={{position:[0,0,8],fov:42}} dpr={[1,1.5]} frameloop={props.reduced||props.mobile||!props.visible?'demand':'always'}><Stars {...props}/></Canvas></Boundary>}
